In [1]:
import numpy as np

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1], [3], [5]])

# A.dot(B)
print(A)
print(B)
print(A @ B)

[[1 2 3]
 [4 5 6]]
[[1]
 [3]
 [5]]
[[22]
 [49]]


In [4]:
C = np.array([1,3,5])

A @ C

array([22, 49])